import os
import json
import base64
from pathlib import Path

# FFmpeg binary location - configurable via environment variable
# On Linux/Render (default): /usr/bin
# On Windows: set FFMPEG_PATH env var to the bin directory containing ffmpeg.exe
_ffmpeg_path_env = os.environ.get("FFMPEG_PATH", None)
if _ffmpeg_path_env:
    FFMPEG_PATH = _ffmpeg_path_env
else:
    # Default Windows path - for local development on Windows
    _local_app_data = os.environ.get("LOCALAPPDATA", None)
    if _local_app_data:
        FFMPEG_PATH = str(Path(_local_app_data) / "Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.1-full_build/bin")
    else:
        # Default Linux path for Render/docker deployment
        FFMPEG_PATH = "/usr/bin"

# Base output directory - configurable via environment variable
# On Linux/Render (default): /tmp/downloads
# On Windows: set OUTPUT_DIR env var or use ~/Videos/YouTube-Downloads
_output_dir_env = os.environ.get("OUTPUT_DIR", None)
if _output_dir_env:
    OUTPUT_DIR = Path(_output_dir_env)
else:
    OUTPUT_DIR = Path(os.path.expanduser("~/Videos/YouTube-Downloads"))

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Temp directory for partial downloads
TEMP_DIR = OUTPUT_DIR / "temp"
TEMP_DIR.mkdir(parents=True, exist_ok=True)

# yt-dlp location hint
YT_DLP_PATH = None  # Will use system yt-dlp if None

# CORS settings for frontend
CORS_ORIGINS = ["http://localhost:5173", "http://127.0.0.1:5173"]

# Cookies directory for YouTube authentication
COOKIES_DIR = Path("/app/cookies")
COOKIES_FILE = COOKIES_DIR / "youtube.txt"

def setup_youtube_cookies():
    """
    Set up YouTube cookies from environment variables.

    Supports two formats:
    1. YOUTUBE_COOKIES - EditThisCookie JSON format (multiline)
    2. YOUTUBE_COOKIES_BASE64 - Base64 encoded Netscape cookie file (single line)

    Cookies are written to /app/cookies/youtube.txt in Netscape format for yt-dlp.
    """
    cookies_json = os.environ.get("YOUTUBE_COOKIES", None)
    cookies_b64 = os.environ.get("YOUTUBE_COOKIES_BASE64", None)

    if cookies_b64:
        # Base64 encoded Netscape cookie file
        try:
            COOKIES_DIR.mkdir(parents=True, exist_ok=True)
            decoded = base64.b64decode(cookies_b64).decode('utf-8')
            with open(COOKIES_FILE, 'w', encoding='utf-8') as f:
                f.write(decoded)
            print("[CONFIG] YouTube cookies loaded from YOUTUBE_COOKIES_BASE64 env var")
            return
        except Exception as e:
            print(f"[CONFIG] Failed to decode YOUTUBE_COOKIES_BASE64: {e}")

    if cookies_json:
        # EditThisCookie JSON format
        try:
            COOKIES_DIR.mkdir(parents=True, exist_ok=True)
            cookies_data = json.loads(cookies_json)

            with open(COOKIES_FILE, 'w', encoding='utf-8') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by YouTube Downloader Backend\n\n")
                for cookie in cookies_data:
                    domain = cookie.get('domain', '.youtube.com')
                    if not domain.startswith('.'):
                        domain = '.' + domain
                    name = cookie.get('name', '')
                    value = cookie.get('value', '')
                    path = cookie.get('path', '/')
                    secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                    expires = str(int(cookie.get('expirationDate', 0)))
                    hostonly = 'FALSE' if cookie.get('hostOnly', False) else 'TRUE'

                    f.write(f"{domain}\t{hostonly}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

            print("[CONFIG] YouTube cookies loaded from YOUTUBE_COOKIES env var")
        except json.JSONDecodeError as e:
            print(f"[CONFIG] Failed to parse YOUTUBE_COOKIES JSON: {e}")
        except Exception as e:
            print(f"[CONFIG] Failed to write cookies file: {e}")
    else:
        print("[CONFIG] YOUTUBE_COOKIES env var not set, using unauthenticated downloads")

# Initialize cookies on module load
setup_youtube_cookies()